<script>CDC.resetToolbar();</script>
<div id="cdcLogin">
  <form id="cdcLoginForm">
    <div class="form-group">
      <label for="cdcLoginFormUsername">Username</label>
      <input type="text" class="form-control" id="cdcLoginFormUsername" name="username" placeholder="Inserisci username">
    </div>
    <div class="form-group">
      <label for="cdcLoginFormPassword">Password</label>
      <input type="password" class="form-control" id="cdcLoginFormPassword" name="password" placeholder="Inserisci password">
    </div>
    <button type="submit" class="btn btn-primary cdc-action" data-cdc-action="AUT" data-cdc-page="LOGIN">Login</button>
  </form>
</div>
