<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('matrix POC')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('../vendor/components/font-awesome/css/fontawesome-all.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/cdc.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/cdc.js'))
        ?>
    </head>
    <body>
      <div id="splashScreen">
        <div class="centerVerHor">
          <i class="fas fa-4x fa-circle-notch fa-spin colorGreen"></i>
        </div>
      </div>
      <div id="content">
    		<div id="top">
    			<div id="logo">
    				<p class="colorGreen">matrix</p>
    			</div>
    			<div class="cdcToolbar" id="toolbarTop">
    				<div>
              <div class="cdcToolbarOption" data-cdc-toolbar="bars"></div>
              <div class="cdcToolbarOption" data-cdc-toolbar="calendar-alt"></div>
              <div class="cdcToolbarOption" data-cdc-toolbar="clock"></div>
    					<div class="cdcToolbarOption" data-cdc-toolbar="user"></div>
    				</div>
    			</div>
    		</div>
    		<div id="body">
    			<div class="cdcToolbar" id="toolbarLeft"></div>
    			<div id="mainContainer">
            <div id="splashScreenMain" style="display: none">
              <div class="centerVerHor">
                <i class="fas fa-4x fa-circle-notch fa-spin colorGreen"></i>
              </div>
            </div>
            <div class="centerVerHor">
              <div id="main">
    				     <?= $this->content ?>
               </div>
            </div>
    			</div>
        </div>
      </div>
      <div id="messageModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
              <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
  		<?= $this->inlineScript() ?>
    </body>
</html>
